version: "3.7"
services:
  postgres:
    image: postgres:15.2
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: sirauth
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sirauth
