// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// RealmsColumns holds the columns for the "realms" table.
	RealmsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
	}
	// RealmsTable holds the schema information for the "realms" table.
	RealmsTable = &schema.Table{
		Name:       "realms",
		Columns:    RealmsColumns,
		PrimaryKey: []*schema.Column{RealmsColumns[0]},
	}
	// ClientsColumns holds the columns for the "clients" table.
	ClientsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "realm_id", Type: field.TypeInt64},
		{Name: "client_secret", Type: field.TypeString},
		{Name: "client_id", Type: field.TypeString},
		{Name: "redirect_urls", Type: field.TypeJSON},
	}
	// ClientsTable holds the schema information for the "clients" table.
	ClientsTable = &schema.Table{
		Name:       "clients",
		Columns:    ClientsColumns,
		PrimaryKey: []*schema.Column{ClientsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		RealmsTable,
		ClientsTable,
	}
)

func init() {
	ClientsTable.Annotation = &entsql.Annotation{
		Table: "clients",
	}
}
