// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"log"

	"sirauth/ent/migrate"

	"sirauth/ent/realm"
	"sirauth/ent/realmoauthclient"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Realm is the client for interacting with the Realm builders.
	Realm *RealmClient
	// RealmOAuthClient is the client for interacting with the RealmOAuthClient builders.
	RealmOAuthClient *RealmOAuthClientClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Realm = NewRealmClient(c.config)
	c.RealmOAuthClient = NewRealmOAuthClientClient(c.config)
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:              ctx,
		config:           cfg,
		Realm:            NewRealmClient(cfg),
		RealmOAuthClient: NewRealmOAuthClientClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:              ctx,
		config:           cfg,
		Realm:            NewRealmClient(cfg),
		RealmOAuthClient: NewRealmOAuthClientClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Realm.
//		Query().
//		Count(ctx)
//
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Realm.Use(hooks...)
	c.RealmOAuthClient.Use(hooks...)
}

// RealmClient is a client for the Realm schema.
type RealmClient struct {
	config
}

// NewRealmClient returns a client for the Realm from the given config.
func NewRealmClient(c config) *RealmClient {
	return &RealmClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `realm.Hooks(f(g(h())))`.
func (c *RealmClient) Use(hooks ...Hook) {
	c.hooks.Realm = append(c.hooks.Realm, hooks...)
}

// Create returns a create builder for Realm.
func (c *RealmClient) Create() *RealmCreate {
	mutation := newRealmMutation(c.config, OpCreate)
	return &RealmCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Realm entities.
func (c *RealmClient) CreateBulk(builders ...*RealmCreate) *RealmCreateBulk {
	return &RealmCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Realm.
func (c *RealmClient) Update() *RealmUpdate {
	mutation := newRealmMutation(c.config, OpUpdate)
	return &RealmUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *RealmClient) UpdateOne(r *Realm) *RealmUpdateOne {
	mutation := newRealmMutation(c.config, OpUpdateOne, withRealm(r))
	return &RealmUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *RealmClient) UpdateOneID(id int) *RealmUpdateOne {
	mutation := newRealmMutation(c.config, OpUpdateOne, withRealmID(id))
	return &RealmUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Realm.
func (c *RealmClient) Delete() *RealmDelete {
	mutation := newRealmMutation(c.config, OpDelete)
	return &RealmDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *RealmClient) DeleteOne(r *Realm) *RealmDeleteOne {
	return c.DeleteOneID(r.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *RealmClient) DeleteOneID(id int) *RealmDeleteOne {
	builder := c.Delete().Where(realm.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &RealmDeleteOne{builder}
}

// Query returns a query builder for Realm.
func (c *RealmClient) Query() *RealmQuery {
	return &RealmQuery{
		config: c.config,
	}
}

// Get returns a Realm entity by its id.
func (c *RealmClient) Get(ctx context.Context, id int) (*Realm, error) {
	return c.Query().Where(realm.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *RealmClient) GetX(ctx context.Context, id int) *Realm {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *RealmClient) Hooks() []Hook {
	return c.hooks.Realm
}

// RealmOAuthClientClient is a client for the RealmOAuthClient schema.
type RealmOAuthClientClient struct {
	config
}

// NewRealmOAuthClientClient returns a client for the RealmOAuthClient from the given config.
func NewRealmOAuthClientClient(c config) *RealmOAuthClientClient {
	return &RealmOAuthClientClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `realmoauthclient.Hooks(f(g(h())))`.
func (c *RealmOAuthClientClient) Use(hooks ...Hook) {
	c.hooks.RealmOAuthClient = append(c.hooks.RealmOAuthClient, hooks...)
}

// Create returns a create builder for RealmOAuthClient.
func (c *RealmOAuthClientClient) Create() *RealmOAuthClientCreate {
	mutation := newRealmOAuthClientMutation(c.config, OpCreate)
	return &RealmOAuthClientCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of RealmOAuthClient entities.
func (c *RealmOAuthClientClient) CreateBulk(builders ...*RealmOAuthClientCreate) *RealmOAuthClientCreateBulk {
	return &RealmOAuthClientCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for RealmOAuthClient.
func (c *RealmOAuthClientClient) Update() *RealmOAuthClientUpdate {
	mutation := newRealmOAuthClientMutation(c.config, OpUpdate)
	return &RealmOAuthClientUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *RealmOAuthClientClient) UpdateOne(roc *RealmOAuthClient) *RealmOAuthClientUpdateOne {
	mutation := newRealmOAuthClientMutation(c.config, OpUpdateOne, withRealmOAuthClient(roc))
	return &RealmOAuthClientUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *RealmOAuthClientClient) UpdateOneID(id int) *RealmOAuthClientUpdateOne {
	mutation := newRealmOAuthClientMutation(c.config, OpUpdateOne, withRealmOAuthClientID(id))
	return &RealmOAuthClientUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for RealmOAuthClient.
func (c *RealmOAuthClientClient) Delete() *RealmOAuthClientDelete {
	mutation := newRealmOAuthClientMutation(c.config, OpDelete)
	return &RealmOAuthClientDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *RealmOAuthClientClient) DeleteOne(roc *RealmOAuthClient) *RealmOAuthClientDeleteOne {
	return c.DeleteOneID(roc.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *RealmOAuthClientClient) DeleteOneID(id int) *RealmOAuthClientDeleteOne {
	builder := c.Delete().Where(realmoauthclient.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &RealmOAuthClientDeleteOne{builder}
}

// Query returns a query builder for RealmOAuthClient.
func (c *RealmOAuthClientClient) Query() *RealmOAuthClientQuery {
	return &RealmOAuthClientQuery{
		config: c.config,
	}
}

// Get returns a RealmOAuthClient entity by its id.
func (c *RealmOAuthClientClient) Get(ctx context.Context, id int) (*RealmOAuthClient, error) {
	return c.Query().Where(realmoauthclient.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *RealmOAuthClientClient) GetX(ctx context.Context, id int) *RealmOAuthClient {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *RealmOAuthClientClient) Hooks() []Hook {
	return c.hooks.RealmOAuthClient
}
