// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sirauth/ent/realmoauthclient"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RealmOAuthClientCreate is the builder for creating a RealmOAuthClient entity.
type RealmOAuthClientCreate struct {
	config
	mutation *RealmOAuthClientMutation
	hooks    []Hook
}

// SetRealmID sets the "realm_id" field.
func (rocc *RealmOAuthClientCreate) SetRealmID(i int64) *RealmOAuthClientCreate {
	rocc.mutation.SetRealmID(i)
	return rocc
}

// SetClientSecret sets the "client_secret" field.
func (rocc *RealmOAuthClientCreate) SetClientSecret(s string) *RealmOAuthClientCreate {
	rocc.mutation.SetClientSecret(s)
	return rocc
}

// SetClientID sets the "client_id" field.
func (rocc *RealmOAuthClientCreate) SetClientID(s string) *RealmOAuthClientCreate {
	rocc.mutation.SetClientID(s)
	return rocc
}

// SetRedirectUrls sets the "redirect_urls" field.
func (rocc *RealmOAuthClientCreate) SetRedirectUrls(s []string) *RealmOAuthClientCreate {
	rocc.mutation.SetRedirectUrls(s)
	return rocc
}

// Mutation returns the RealmOAuthClientMutation object of the builder.
func (rocc *RealmOAuthClientCreate) Mutation() *RealmOAuthClientMutation {
	return rocc.mutation
}

// Save creates the RealmOAuthClient in the database.
func (rocc *RealmOAuthClientCreate) Save(ctx context.Context) (*RealmOAuthClient, error) {
	var (
		err  error
		node *RealmOAuthClient
	)
	if len(rocc.hooks) == 0 {
		if err = rocc.check(); err != nil {
			return nil, err
		}
		node, err = rocc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*RealmOAuthClientMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = rocc.check(); err != nil {
				return nil, err
			}
			rocc.mutation = mutation
			if node, err = rocc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(rocc.hooks) - 1; i >= 0; i-- {
			if rocc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = rocc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, rocc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (rocc *RealmOAuthClientCreate) SaveX(ctx context.Context) *RealmOAuthClient {
	v, err := rocc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rocc *RealmOAuthClientCreate) Exec(ctx context.Context) error {
	_, err := rocc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rocc *RealmOAuthClientCreate) ExecX(ctx context.Context) {
	if err := rocc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (rocc *RealmOAuthClientCreate) check() error {
	if _, ok := rocc.mutation.RealmID(); !ok {
		return &ValidationError{Name: "realm_id", err: errors.New(`ent: missing required field "RealmOAuthClient.realm_id"`)}
	}
	if _, ok := rocc.mutation.ClientSecret(); !ok {
		return &ValidationError{Name: "client_secret", err: errors.New(`ent: missing required field "RealmOAuthClient.client_secret"`)}
	}
	if _, ok := rocc.mutation.ClientID(); !ok {
		return &ValidationError{Name: "client_id", err: errors.New(`ent: missing required field "RealmOAuthClient.client_id"`)}
	}
	if _, ok := rocc.mutation.RedirectUrls(); !ok {
		return &ValidationError{Name: "redirect_urls", err: errors.New(`ent: missing required field "RealmOAuthClient.redirect_urls"`)}
	}
	return nil
}

func (rocc *RealmOAuthClientCreate) sqlSave(ctx context.Context) (*RealmOAuthClient, error) {
	_node, _spec := rocc.createSpec()
	if err := sqlgraph.CreateNode(ctx, rocc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (rocc *RealmOAuthClientCreate) createSpec() (*RealmOAuthClient, *sqlgraph.CreateSpec) {
	var (
		_node = &RealmOAuthClient{config: rocc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: realmoauthclient.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: realmoauthclient.FieldID,
			},
		}
	)
	if value, ok := rocc.mutation.RealmID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: realmoauthclient.FieldRealmID,
		})
		_node.RealmID = value
	}
	if value, ok := rocc.mutation.ClientSecret(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: realmoauthclient.FieldClientSecret,
		})
		_node.ClientSecret = value
	}
	if value, ok := rocc.mutation.ClientID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: realmoauthclient.FieldClientID,
		})
		_node.ClientID = value
	}
	if value, ok := rocc.mutation.RedirectUrls(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeJSON,
			Value:  value,
			Column: realmoauthclient.FieldRedirectUrls,
		})
		_node.RedirectUrls = value
	}
	return _node, _spec
}

// RealmOAuthClientCreateBulk is the builder for creating many RealmOAuthClient entities in bulk.
type RealmOAuthClientCreateBulk struct {
	config
	builders []*RealmOAuthClientCreate
}

// Save creates the RealmOAuthClient entities in the database.
func (roccb *RealmOAuthClientCreateBulk) Save(ctx context.Context) ([]*RealmOAuthClient, error) {
	specs := make([]*sqlgraph.CreateSpec, len(roccb.builders))
	nodes := make([]*RealmOAuthClient, len(roccb.builders))
	mutators := make([]Mutator, len(roccb.builders))
	for i := range roccb.builders {
		func(i int, root context.Context) {
			builder := roccb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RealmOAuthClientMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, roccb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, roccb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, roccb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (roccb *RealmOAuthClientCreateBulk) SaveX(ctx context.Context) []*RealmOAuthClient {
	v, err := roccb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (roccb *RealmOAuthClientCreateBulk) Exec(ctx context.Context) error {
	_, err := roccb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (roccb *RealmOAuthClientCreateBulk) ExecX(ctx context.Context) {
	if err := roccb.Exec(ctx); err != nil {
		panic(err)
	}
}
