// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"sirauth/ent/predicate"
	"sirauth/ent/realmoauthclient"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RealmOAuthClientDelete is the builder for deleting a RealmOAuthClient entity.
type RealmOAuthClientDelete struct {
	config
	hooks    []Hook
	mutation *RealmOAuthClientMutation
}

// Where appends a list predicates to the RealmOAuthClientDelete builder.
func (rocd *RealmOAuthClientDelete) Where(ps ...predicate.RealmOAuthClient) *RealmOAuthClientDelete {
	rocd.mutation.Where(ps...)
	return rocd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (rocd *RealmOAuthClientDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(rocd.hooks) == 0 {
		affected, err = rocd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*RealmOAuthClientMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			rocd.mutation = mutation
			affected, err = rocd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(rocd.hooks) - 1; i >= 0; i-- {
			if rocd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = rocd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, rocd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (rocd *RealmOAuthClientDelete) ExecX(ctx context.Context) int {
	n, err := rocd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (rocd *RealmOAuthClientDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: realmoauthclient.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: realmoauthclient.FieldID,
			},
		},
	}
	if ps := rocd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, rocd.driver, _spec)
}

// RealmOAuthClientDeleteOne is the builder for deleting a single RealmOAuthClient entity.
type RealmOAuthClientDeleteOne struct {
	rocd *RealmOAuthClientDelete
}

// Exec executes the deletion query.
func (rocdo *RealmOAuthClientDeleteOne) Exec(ctx context.Context) error {
	n, err := rocdo.rocd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{realmoauthclient.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (rocdo *RealmOAuthClientDeleteOne) ExecX(ctx context.Context) {
	rocdo.rocd.ExecX(ctx)
}
