// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Realm is the predicate function for realm builders.
type Realm func(*sql.Selector)

// RealmOAuthClient is the predicate function for realmoauthclient builders.
type RealmOAuthClient func(*sql.Selector)
